2025-09-19 04:25:02,761 - __main__ - INFO - 🚀 Запуск бота...
2025-09-19 04:25:03,552 - __main__ - INFO - 🔧 Создаю JWT и получаю IAM_TOKEN...
2025-09-19 04:25:03,553 - __main__ - INFO - 🔑 JWT создан, IAM_TOKEN получен
2025-09-19 04:25:06,828 - rag_yandex_nofaiss - INFO - Processed cocktail_book.pdf -> 2 chunks
2025-09-19 04:25:06,828 - rag_yandex_nofaiss - INFO - Building FAISS index for 2 docs via faiss_index_yandex.build_index...
2025-09-19 04:25:07,995 - yandex_api - ERROR - Embedding error 401 {"error":"Unknown api key '****'","code":16,"message":"Unknown api key '****'","details":[]}
2025-09-19 04:25:08,035 - rag_yandex_nofaiss - ERROR - faiss_adapter.build_index failed: Embedding error: 401
Traceback (most recent call last):
  File "F:\Work_with_maks\yandex\rag_yandex_nofaiss.py", line 149, in build_vectorstore_from_docs
    return build_index(docs, model_uri=embedding_model_uri)
  File "F:\Work_with_maks\yandex\faiss_index_yandex.py", line 23, in build_index
    embeddings = yandex_batch_embeddings(texts, model_uri=model_uri)  # list of vectors
  File "F:\Work_with_maks\yandex\yandex_api.py", line 34, in yandex_batch_embeddings
    out.append(yandex_text_embedding(t, model_uri=model_uri))
               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Work_with_maks\yandex\yandex_api.py", line 23, in yandex_text_embedding
    raise RuntimeError(f"Embedding error: {r.status_code}")
RuntimeError: Embedding error: 401
2025-09-19 04:25:08,040 - rag_yandex_nofaiss - INFO - Falling back to numpy save (vectors.npy + meta.pkl).
2025-09-19 04:25:09,043 - yandex_api - ERROR - Embedding error 401 {"error":"Unknown api key '****'","code":16,"message":"Unknown api key '****'","details":[]}
